package by.epam.naumovich.film_ordering.controller;

public enum CommandName {
	CHANGE_LANGUAGE,
	CHANGE_USER_SETTINGS,
	GET_NOVELTY,
	GET_SIDEBAR_NEWS,
	LOGIN, 
	LOGOUT,
	OPEN_ABOUT_US_PAGE,
	OPEN_ALL_ORDERS,
	OPEN_ALL_REVIEWS,
	OPEN_FEEDBACK_PAGE,
	OPEN_FILM_LIST, 
	OPEN_FILM_PAGE, 
	OPEN_HELP_PAGE,
	OPEN_LOGINATION_PAGE,
	OPEN_NEW_REVIEW_PAGE,
	OPEN_NEWS_LIST, 
	OPEN_ORDER_PAGE, 
	OPEN_SIGN_UP_PAGE,
	OPEN_SINGLE_NEWS,
	OPEN_USER_ORDERS,
	OPEN_USER_PROFILE,
	OPEN_USER_REVIEWS,
	OPEN_USER_SETTINGS,
	OPEN_WIDEN_SEARCH_PAGE,
	SIGN_UP
}
