package by.epam.naumovich.film_ordering.controller;

public enum CommandName {
	CHANGE_LANGUAGE,
	GET_NOVELTY,
	GET_SIDEBAR_NEWS,
	LOGIN, 
	LOGOUT,
	OPEN_ALL_ORDERS,
	OPEN_ALL_REVIEWS,
	OPEN_FILM_LIST, 
	OPEN_FILM_PAGE, 
	OPEN_NEWS_LIST, 
	OPEN_ORDER_PAGE, 
	OPEN_PROFILE,
	OPEN_SINGLE_NEWS,
	OPEN_USER_ORDERS,
	OPEN_USER_REVIEWS
}
